controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


position_controller:
  ros__parameters:
    update_rate: 50 # Hz
    joints:
      - camera_L_pan_joint
      - camera_L_tilt_joint
      - camera_R_pan_joint
      - camera_R_tilt_joint
    interface_name: position

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 20 # Hz
    joints:
      - camera_L_pan_joint
      - camera_L_tilt_joint
      - camera_R_pan_joint
      - camera_R_tilt_joint
    interfaces:
      - position
